import Head from "next/head";
import GameDevHero from "./GameDevHero";
import ComputerScience from "./ComputerScience";
import Interests from "./Interests";
import ContactMe from "./ContactMe";
import { useState } from "react";
import Base from "./Base";
import { AnimatePresence, motion } from "framer-motion";
export default function Home() {
  const [page, setPage] = useState("");
  const [exitMotion, setExitMotion] = useState({});
  console.log(page);
  if (page === "GameDev") {
    setExitMotion({
      scale: 0,
    });
  }
  return (
    <div className="cover">
      <Head>
        <title>Le theOmegaWolf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dflex alignVertical cover">
        <AnimatePresence>
          {page === "" ? (
            <motion.div
              key="base"
              exit={exitMotion}
              className={"cover"}
              transition={{ type: "spring", duration: 0.8 }}
            >
              <Base setPage={setPage} />
            </motion.div>
          ) : (
            <></>
          )}
          {page === "Gamedev" ? <GameDevHero /> : <></>}
        </AnimatePresence>
      </div>
      {/* <div className="dflex alignVertical cover">
        <Interests />
      </div>
      <div className="dflex alignVertical cover">
        <ContactMe />
      </div> */}
    </div>
  );
}
